services:
  grocy-ourgroceries-test:
    build: .
    container_name: grocy-ourgroceries-test
    volumes:
      - ./config.json:/app/config.json
      - ./sync_tracking.json:/app/sync_tracking.json
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PYTHONPATH=/app
    command: pytest --cov=clients --cov=sync --cov=utils
